---
- name: Checking if database {{ guacamole_db_name }} exists
  shell: mysql -e 'SHOW DATABASES;' | grep {{ guacamole_db_name }}
  register: database_status
  changed_when: false
  failed_when: false
  
- name: Creating guacamole database
  mysql_db:
    name: "{{ guacamole_db_name }}"
    state: present
  when: database_status.stdout == ""

- name: Creating mysql user {{ guacamole_db_user }}
  mysql_user:
    name: "{{ guacamole_db_user }}"
    password: "{{ guacamole_db_password }}"
    priv: '{{ guacamole_db_name }}.*:SELECT,INSERT,UPDATE,DELETE'
    host: "{{ guacamole_db_client }}"
    state: present

- name: Importing guacamole schema
  mysql_db:
    state: import
    name: "{{ guacamole_db_name }}"
    target: /tmp/guacamole-auth-jdbc-{{ guacamole_version }}/mysql/schema/001-create-schema.sql
  when: database_status.stdout == ""

- name: Importing guacamole user 'guacadmin'
  mysql_db:
    state: import
    name: "{{ guacamole_db_name }}"
    target: /tmp/guacamole-auth-jdbc-{{ guacamole_version }}/mysql/schema/002-create-admin-user.sql
  when: database_status.stdout == ""
